// Code generated by sqlc. DO NOT EDIT.

package pg

import (
	"time"
)

type Follower struct {
	ID         int       `json:"id"`
	CreatedAt  time.Time `json:"createdAt"`
	LeaderID   int       `json:"leader_id"`
	FollowerID int       `json:"follower_id"`
}

func (Follower) IsEntity() {}

type NewFollower struct {
	LeaderID   int `json:"leader_id"`
	FollowerID int `json:"follower_id"`
}

type User struct {
	ID        int        `json:"id"`
	Followers []Follower `json:"followers"`
}

func (User) IsEntity() {}
