CREATE TABLE post_likes (
	id SERIAL PRIMARY KEY,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
	user_id INTEGER NOT NULL UNIQUE,
	post_id INTEGER NOT NULL
);

CREATE TABLE comment_likes (
	id SERIAL PRIMARY KEY,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
	user_id INTEGER NOT NULL UNIQUE,
	comment_id INTEGER NOT NULL
);
