// Code generated by sqlc. DO NOT EDIT.

package pg

import (
	"time"
)

type EditUser struct {
	ID     int     `json:"id"`
	Bio    *string `json:"bio"`
	Avatar *string `json:"avatar"`
}

type NewUser struct {
	Username string  `json:"username"`
	Bio      *string `json:"bio"`
	Avatar   *string `json:"avatar"`
	Email    *string `json:"email"`
	Password string  `json:"password"`
}

type Post struct {
	UserID int `json:"user_id"`
}

func (Post) IsEntity() {}

type User struct {
	ID        int       `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	Username  string    `json:"username"`
	Bio       *string   `json:"bio"`
	Avatar    *string   `json:"avatar"`
	Email     *string   `json:"email"`
	Password  string    `json:"password"`
	Posts     []*Post   `json:"posts"`
}

func (User) IsEntity() {}

type Comment struct {
	UserID int      `json:"user_id"`
	User   *User `json:"user"`
}

func (Comment) IsEntity() {}

type CommentLike struct {
	UserID int      `json:"user_id"`
	User   *User `json:"user"`
}

func (CommentLike) IsEntity() {}

type PostLike struct {
	UserID int      `json:"user_id"`
	User   *User `json:"user"`
}

func (PostLike) IsEntity() {}


type Follower struct {
	ID   int      `json:"id"`
	User *User `json:"user"`
}

func (Follower) IsEntity() {}