apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
  template:
    metadata:
      labels:
        app: reviews
    spec:
      containers:
      - name: reviews
        image: cesargdd/kub-demo-reviews:latest
