// Code generated by sqlc. DO NOT EDIT.

package pg

import (
	"time"
)

type Comment struct {
	PostID int `json:"post_id"`
}

func (Comment) IsEntity() {}

type EditPost struct {
	ID      int     `json:"id"`
	URL     *string `json:"url"`
	Caption *string `json:"caption"`
}

type HashtagPost struct {
	PostID int    `json:"post_id"`
	Posts  []Post `json:"posts"`
}

func (HashtagPost) IsEntity() {}

type NewPost struct {
	URL     string  `json:"url"`
	Caption *string `json:"caption"`
	UserID  int     `json:"userId"`
}

type Post struct {
	ID        int       `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	URL       string    `json:"url"`
	Caption   *string   `json:"caption"`
	UserID    int       `json:"user_id"`
}

func (Post) IsEntity() {}

type PostLike struct {
	PostID int `json:"post_id"`
}

func (PostLike) IsEntity() {}

type User struct {
	ID    int    `json:"id"`
	Posts []Post `json:"posts"`
}

func (User) IsEntity() {}

