CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
	username VARCHAR(30) UNIQUE NOT NULL,
	bio VARCHAR(400) NOT NULL DEFAULT '\',
	avatar VARCHAR(200) NOT NULL DEFAULT '\',
	email VARCHAR(40) NOT NULL,
	password VARCHAR(50) NOT NULL
);

