// Code generated by sqlc. DO NOT EDIT.

package pg

import (
	"time"
)

type CommentLike struct {
	ID        int       `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
	UserID    int       `json:"user_id"`
	CommentID int       `json:"commentId"`
	User      *User     `json:"user"`
}

func (CommentLike) IsEntity() {}

type NewCommentLike struct {
	UserID    int `json:"user_id"`
	CommentID int `json:"comment_id"`
}

type NewPostLike struct {
	UserID int `json:"user_id"`
	PostID int `json:"post_id"`
}

type PostLike struct {
	ID        int       `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
	UserID    int       `json:"user_id"`
	PostID    int       `json:"post_id"`
	User      *User     `json:"user"`
}

func (PostLike) IsEntity() {}

type User struct {
	ID int `json:"id"`
}

func (User) IsEntity() {}

type Post struct {
	ID        int           `json:"id"`
	PostLikes []PostLike `json:"postLikes"`
}

func (Post) IsEntity() {}

type Comment struct {
	ID           int              `json:"id"`
	CommentLikes []CommentLike `json:"commentLikes"`
}

func (Comment) IsEntity() {}