// Code generated by sqlc. DO NOT EDIT.

package pg

import (
	"time"
)

type Comment struct {
	ID        int           `json:"id"`
	CreatedAt time.Time     `json:"createdAt"`
	UpdatedAt time.Time     `json:"updatedAt"`
	Contents  string        `json:"contents"`
	UserID    int           `json:"user_id"`
	PostID    int           `json:"post_id"`
	Likes     []CommentLike `json:"likes"`
}

func (Comment) IsEntity() {}

type CommentLike struct {
	ID int `json:"id"`
}

func (CommentLike) IsEntity() {}

type EditComment struct {
	ID       int    `json:"id"`
	Contents string `json:"contents"`
}

type NewComment struct {
	Contents string `json:"contents"`
	UserID   int    `json:"user_id"`
	PostID   int    `json:"post_id"`
}


type User struct {
	ID int `json:"id"`
}

func (User) IsEntity() {}

type Post struct {
	ID       int          `json:"id"`
	Comments []Comment `json:"comments"`
}

func (Post) IsEntity() {}